<?php
declare(strict_types=1);

/*
 * Gemeinsame Standard-Inhalte.
 *
 * Diese Datei ist die einzige Quelle fuer die Startinhalte. Sie wird von zwei
 * Stellen genutzt:
 *   1. app/schema.php (seed_defaults) schreibt sie beim Install in die Datenbank.
 *   2. app/helpers.php nutzt sie als Fallback, wenn keine Datenbank erreichbar
 *      ist (Vorschau-/Demo-Modus, z. B. bei einem Vercel-Deployment ohne MySQL).
 *
 * So sieht die Seite auch ohne Datenbank vollstaendig gestaltet aus; sobald eine
 * echte Datenbank angebunden ist, uebernimmt automatisch der Datenbankinhalt.
 */

return [
    // setting_key => [value, label, group, field_type]
    'settings' => [
        'site_name' => ['Unternehmenspflichten.de', 'Seitentitel', 'general', 'text'],
        'site_claim' => ['Nichts vergessen. Alles nachweisen koennen.', 'Hauptclaim', 'content', 'textarea'],
        'site_subclaim' => ['Fristen, Pflichtnachweise und Portalbelege fuer Haendler, Importeure und Betriebe zentral ablegen, erinnern lassen und als Nachweisordner exportieren.', 'Unterzeile', 'content', 'textarea'],
        'primary_cta_label' => ['Nachweisordner starten', 'Primaerer Button', 'content', 'text'],
        'primary_cta_url' => ['/kontakt', 'Primaerer Button-Link', 'content', 'text'],
        'secondary_cta_label' => ['Beispiel ansehen', 'Sekundaerer Button', 'content', 'text'],
        'secondary_cta_url' => ['/module', 'Sekundaerer Button-Link', 'content', 'text'],
        'hero_eyebrow' => ['Nachweise statt Rechtsurteil', 'Hero Eyebrow', 'content', 'text'],
        'home_modules_heading' => ['Startpunkt: die Produkt- und Haendler-Nachweisakte', 'Startseite: Modul-Ueberschrift', 'content', 'text'],
        'home_modules_intro' => ['Zuerst dort, wo der Druck am groessten ist: GPSR, VerpackG/LUCID und die neuen EU-Pflichten fuer Haendler und Importeure. Pruef-/Fristen-Tracker und weitere Akten folgen als Ausbaustufen.', 'Startseite: Modul-Einleitung', 'content', 'textarea'],
        'home_modules_eyebrow' => ['Startfokus', 'Startseite: Modul-Eyebrow', 'content', 'text'],
        'home_process_heading' => ['Der Ablauf bleibt bewusst einfach', 'Startseite: Ablauf-Ueberschrift', 'content', 'text'],
        'home_process_eyebrow' => ['Ablauf', 'Startseite: Ablauf-Eyebrow', 'content', 'text'],
        'home_step_1_title' => ['Frist oder Objekt anlegen', 'Startseite: Schritt 1 Titel', 'content', 'text'],
        'home_step_1_text' => ['Betrieb, Berater oder Fachkraft legt an, was beobachtet werden soll.', 'Startseite: Schritt 1 Text', 'content', 'textarea'],
        'home_step_2_title' => ['Belege sichern', 'Startseite: Schritt 2 Titel', 'content', 'text'],
        'home_step_2_text' => ['Quittungen, Fotos, Protokolle, Portalbelege und Bescheide werden abgelegt.', 'Startseite: Schritt 2 Text', 'content', 'textarea'],
        'home_step_3_title' => ['Export erstellen', 'Startseite: Schritt 3 Titel', 'content', 'text'],
        'home_step_3_text' => ['Nachweisordner fuer Steuerberater, Pruefer, Sifa, Auftraggeber oder interne Kontrolle.', 'Startseite: Schritt 3 Text', 'content', 'textarea'],
        'home_trust_heading' => ['Keine Rechtsberatung. Saubere Nachweisarbeit.', 'Startseite: Vertrauens-Ueberschrift', 'content', 'text'],
        'home_trust_eyebrow' => ['Grenze', 'Startseite: Vertrauens-Eyebrow', 'content', 'text'],
        'faq_eyebrow' => ['FAQ', 'FAQ Eyebrow', 'content', 'text'],
        'faq_heading' => ['Haeufige Fragen', 'FAQ Ueberschrift', 'content', 'text'],
        'legal_boundary' => ['Die fachliche Bewertung bleibt beim Betrieb und seinen Beratern. Die Plattform verwaltet Fristen, Dokumente, Belege und Exporte.', 'Rechtsgrenze', 'content', 'textarea'],
        'contact_email' => ['kontakt@unternehmenspflichten.de', 'Kontakt E-Mail', 'contact', 'text'],
        'contact_phone' => ['', 'Telefon', 'contact', 'text'],
        'company_name' => ['Unternehmenspflichten.de', 'Betreibername', 'legal', 'text'],
        'company_address' => ['Bitte im Admin ersetzen', 'Anschrift', 'legal', 'textarea'],
        'pricing_note' => ['Startpakete werden individuell nach Nutzerzahl, Standorten und Nachweisumfang eingerichtet.', 'Preishinweis', 'content', 'textarea'],
    ],

    // token_key => [value, label, field_type]
    'design' => [
        'color-bg' => ['#f6f7f4', 'Hintergrund', 'color'],
        'color-surface' => ['#ffffff', 'Flaeche', 'color'],
        'color-text' => ['#17211d', 'Text', 'color'],
        'color-muted' => ['#5b6762', 'Sekundaertext', 'color'],
        'color-primary' => ['#0f5b55', 'Primaerfarbe', 'color'],
        'color-primary-strong' => ['#0a413d', 'Primaer dunkel', 'color'],
        'color-secondary' => ['#275f8f', 'Info-Blau', 'color'],
        'color-accent' => ['#c47a1b', 'Fristen-Akzent', 'color'],
        'color-danger' => ['#a63a2b', 'Ueberfaellig', 'color'],
        'color-success' => ['#2f7d4f', 'Erledigt', 'color'],
        'font-head' => ['Inter, Arial, sans-serif', 'Schrift Ueberschriften', 'text'],
        'font-body' => ['Inter, Arial, sans-serif', 'Schrift Text', 'text'],
        'base-font-size' => ['16px', 'Basis-Schriftgroesse', 'text'],
        'radius' => ['8px', 'Eckenradius', 'text'],
        'max-width' => ['1180px', 'Maximale Breite', 'text'],
    ],

    // [slug, nav_label, title, hero_title, hero_subtitle, cta_label, cta_url, body_html, meta_title, meta_description, sort_order, show_in_nav]
    'pages' => [
        ['home', 'Start', 'Fristen, Pruefungen und Nachweise fuer Betriebe', 'Nichts vergessen. Alles nachweisen koennen.', 'Fristen, Pflichtnachweise und Portalbelege fuer Haendler, Importeure und Betriebe zentral ablegen, erinnern lassen und als Nachweisordner exportieren.', 'Demo anfragen', '/kontakt', '<h2>Worum es geht</h2><p>Unternehmenspflichten.de ist als schlanke Nachweisplattform fuer Betriebe geplant: Fristen eintragen, Unterlagen ablegen, Portalbelege sichern und Exportordner fuer Steuerberater, Pruefer, Sifa oder Auftraggeber erstellen.</p><p>Die Plattform ersetzt keine fachliche Beratung. Sie hilft beim Verwalten, Erinnern und Wiederfinden.</p>', 'Unternehmenspflichten, Fristen und Nachweise zentral verwalten', 'Fristen, Pruefungen, Portalbelege und Nachweisordner fuer Betriebe zentral verwalten.', 1, 1],
        ['module', 'Module', 'Module fuer Fristen, Pruefungen und Nachweise', 'Start mit zwei klaren Keilen', 'Pruef-/Fristen-Tracker und Produkt-/Haendler-Nachweisakte bilden den Start. Weitere Bereiche bleiben Roadmap.', 'Kontakt aufnehmen', '/kontakt', '<p>Alle Module sind ueberschreibbar: Texte, Quellen, Status, Reihenfolge und Call-to-Actions koennen im Admin angepasst werden.</p>', 'Module fuer Unternehmenspflichten und Nachweise', 'Startmodule und Roadmap fuer Unternehmenspflichten.de.', 2, 1],
        ['berater', 'Berater', 'Beraterzugang fuer Steuerberater, Sifa und Dienstleister', 'Mandantenunterlagen schneller bekommen', 'Steuerberater, Lohnbueros, Sifa, Pruefer und Fachberater sollen Nachweise strukturieren, anfordern und exportieren koennen.', 'Beraterzugang anfragen', '/kontakt', '<p>Der Beraterzugang ist als Vertriebskanal und Produktnutzen gedacht: Mandanten liefern Belege, Verantwortliche sehen offene Punkte, Exporte werden sauber vorbereitet.</p>', 'Beraterzugang fuer Unternehmenspflichten.de', 'Mandantenunterlagen, Fristen und Belege fuer Steuerberater, Lohnbueros und Sifa strukturieren.', 3, 1],
        ['preise', 'Preise', 'Pakete fuer Betriebe und Berater', 'Ein Abo um Fristen, Belege und Exporte', 'Preise skalieren nach Nutzern, Standorten, Objekten, Produkten und Beraterzugang.', 'Angebot anfragen', '/kontakt', '<h2>Startlogik</h2><p>Basis fuer kleine Betriebe, Pro fuer mehrere Standorte oder viele Produkte, Beraterpakete fuer Mandantenverwaltung. Finale Preise koennen im Admin ersetzt werden.</p>', 'Preise fuer Unternehmenspflichten.de', 'Pakete fuer Betriebe, Produktanbieter und Berater.', 4, 1],
        ['kontakt', 'Kontakt', 'Demo oder Startpaket anfragen', 'Lass uns den ersten Nachweisordner sauber aufsetzen', 'Beschreibe kurz Betrieb, Branche und welches Fristen- oder Produktnachweisproblem zuerst geloest werden soll.', 'Nachricht senden', '#kontaktformular', '<p>Kontaktanfragen werden in der Datenbank gespeichert und koennen im Admin bearbeitet werden. SMTP kann spaeter ergaenzt werden.</p>', 'Kontakt zu Unternehmenspflichten.de', 'Demo, Startpaket oder Beraterzugang fuer Unternehmenspflichten.de anfragen.', 5, 1],
        ['impressum', 'Impressum', 'Impressum', 'Angaben gemaess DDG', 'Diese Angaben sind Platzhalter und muessen vor dem Live-Betrieb im Admin ersetzt werden.', null, null, '<p><strong>Betreiber:</strong> Bitte im Admin ersetzen</p><p><strong>Anschrift:</strong> Bitte im Admin ersetzen</p><p><strong>E-Mail:</strong> kontakt@unternehmenspflichten.de</p>', 'Impressum', 'Impressum von Unternehmenspflichten.de.', 90, 0],
        ['datenschutz', 'Datenschutz', 'Datenschutzerklaerung', 'Datenschutz und Kontaktanfragen', 'Diese Datenschutzerklaerung ist ein editierbarer Starttext und muss vor dem Live-Betrieb final geprueft werden.', null, null, '<h2>Kontaktformular</h2><p>Wenn Sie das Kontaktformular nutzen, speichern wir Ihre Angaben zur Bearbeitung der Anfrage.</p><h2>Server-Logs</h2><p>Der Hostinganbieter kann technische Zugriffsdaten verarbeiten. Details muessen nach Hosting-Konfiguration ergaenzt werden.</p><h2>Keine Rechtsberatung</h2><p>Die Plattform dient der Organisation von Fristen, Dokumenten und Nachweisen.</p>', 'Datenschutz', 'Datenschutzhinweise fuer Unternehmenspflichten.de.', 91, 0],
        ['ratgeber', 'Ratgeber', 'Ratgeber zu Unternehmenspflichten', 'Ratgeber: Pflichten, Fristen und Nachweise', 'Konkrete Antworten zu wiederkehrenden Unternehmenspflichten und den Belegen, die man dafuer vorhalten sollte.', 'Nachweisordner starten', '/kontakt', '<p>Kurz und konkret: was gilt, welche Fristen und Nachweise wichtig sind und wie die Belege pruefsicher abgelegt werden. Allgemeine Information, keine Rechtsberatung.</p>', 'Ratgeber zu Unternehmenspflichten, Fristen und Nachweisen', 'Konkrete Ratgeber zu GPSR, LUCID, DGUV V3, E-Rechnung, KI-Verordnung und Offenlegung: Pflichten, Fristen und die richtigen Nachweise.', 6, 1],
        ['gpsr-nachweispflichten-haendler', 'GPSR-Nachweise', 'GPSR Nachweispflichten fuer Haendler', 'GPSR: Welche Nachweise muss ich als Haendler vorhalten?', 'Seit dem 13.12.2024 gilt die EU-Produktsicherheitsverordnung (GPSR). Ueberblick ueber Pflichten, typische Nachweise und ihre Ablage.', 'Produktakte starten', '/kontakt', '<h2>Worum es geht</h2><p>Die EU-Produktsicherheitsverordnung (GPSR, Verordnung (EU) 2023/988) gilt seit dem 13. Dezember 2024 fuer nahezu alle Verbraucherprodukte ohne eigene Spezialvorschrift. Sie verpflichtet Hersteller, Importeure und Haendler zu Sicherheit, Rueckverfolgbarkeit und Information.</p><h2>Typische Nachweise, die Haendler vorhalten</h2><ul><li>verantwortliche Person mit Sitz in der EU je Produkt</li><li>Herstellerangaben sowie Typen-, Chargen- oder Seriennummer zur Rueckverfolgbarkeit</li><li>Sicherheits- und Warnhinweise sowie Anleitung in Landessprache</li><li>technische Unterlagen bzw. Nachweise vom Vorlieferanten</li><li>Dokumentation von Beschwerden, Ruecknahmen und Korrekturmassnahmen</li></ul><h2>Haeufige Fragen</h2><h3>Brauche ich fuer jedes Produkt einen EU-Ansprechpartner?</h3><p>Fuer Produkte aus Drittlaendern muss ein Wirtschaftsakteur mit Sitz in der EU benannt und erreichbar sein. Ohne diesen darf das Produkt nicht angeboten werden.</p><h3>Was droht bei Verstoessen?</h3><p>Marktueberwachung, Verkaufsstopp und Abmahnungen sind moeglich. Erste Abmahnungen wegen fehlender GPSR-Angaben sind dokumentiert.</p><p><strong>Hinweis:</strong> Allgemeine Information, keine Rechtsberatung. Die Nachweisakte hilft beim Sammeln, Zuordnen und Exportieren der Unterlagen; die fachliche Bewertung bleibt bei Betrieb und Beratern.</p>', 'GPSR Nachweispflichten fuer Haendler und Importeure', 'GPSR ab 12/2024: Welche Nachweise Haendler und Importeure vorhalten und wie sie eine pruefsichere Produktakte aufbauen.', 200, 0],
        ['lucid-verpackungsregister-nachweis', 'LUCID/VerpackG', 'LUCID und VerpackG Nachweise', 'LUCID/VerpackG: Registrierung, Lizenz und Nachweise richtig ablegen', 'Registrierung, Systembeteiligung und Mengenmeldung erzeugen Belege, die dauerhaft auffindbar sein muessen. Ueberblick und Ablage.', 'Nachweisakte starten', '/kontakt', '<h2>Die drei Pflichtschritte</h2><ul><li><strong>Registrierung</strong> im Verpackungsregister LUCID bei der Zentralen Stelle vor dem Inverkehrbringen</li><li><strong>Systembeteiligung</strong> (Lizenzierung) der Verpackungsmengen bei einem dualen System</li><li><strong>Datenmeldung</strong> der lizenzierten Mengen an LUCID</li></ul><h2>Typische Belege in der Akte</h2><ul><li>LUCID-Registriernummer und Registrierungsbestaetigung</li><li>Lizenz- bzw. Beteiligungsvertrag mit dem dualen System</li><li>Mengenmeldungen und Jahresabschluss-Mengen</li><li>bei Ueberschreiten der Schwellen: Vollstaendigkeitserklaerung</li></ul><h2>Ausblick</h2><p>Ab August 2026 loest die EU-Verpackungsverordnung (PPWR) schrittweise das VerpackG ab. Bestehende Registrierungen und Belege sollten geordnet vorliegen, um den Uebergang nachvollziehbar zu halten.</p><p><strong>Hinweis:</strong> Allgemeine Information, keine Rechtsberatung. Die Lizenzierung selbst erfolgt beim dualen System; die Plattform legt die Belege ab und erinnert an Fristen.</p>', 'LUCID und VerpackG: Registrierung, Lizenz und Nachweise', 'LUCID-Registrierung, Systembeteiligung und Mengenmeldung: welche Belege Haendler ablegen und wie der PPWR-Uebergang vorbereitet wird.', 210, 0],
        ['dguv-v3-pruefung-nachweis', 'DGUV V3', 'DGUV V3 Pruefung Nachweis', 'DGUV V3 Pruefung: Fristen und Nachweise dokumentieren', 'Elektrische Betriebsmittel muessen regelmaessig geprueft und die Pruefung dokumentiert werden. Ueberblick ueber Nachweise und Ablage.', 'Fristen-Tracker ansehen', '/kontakt', '<h2>Worum es geht</h2><p>Die DGUV Vorschrift 3 verlangt die regelmaessige Pruefung ortsveraenderlicher und ortsfester elektrischer Betriebsmittel durch eine Elektrofachkraft. Die konkreten Pruefintervalle ergeben sich aus der Gefaehrdungsbeurteilung und den technischen Regeln (u. a. TRBS 1201/1203).</p><h2>Typische Nachweise</h2><ul><li>Pruefprotokoll je Geraet oder Anlage mit Ergebnis und Datum</li><li>Angaben zur pruefenden Elektrofachkraft</li><li>Maengel- und Massnahmenliste</li><li>naechster Prueftermin und Verantwortlicher</li></ul><h2>Haeufige Fragen</h2><h3>Wie oft muss geprueft werden?</h3><p>Es gibt keine starre Einheitsfrist. Der Intervall folgt aus der Gefaehrdungsbeurteilung; Richtwerte je Geraeteart dienen als Orientierung.</p><h3>Wer darf pruefen?</h3><p>Nur eine qualifizierte Elektrofachkraft nach den anerkannten Regeln der Technik.</p><p><strong>Hinweis:</strong> Allgemeine Information, keine Rechtsberatung. Die Plattform verwaltet Fristen und Protokolle; die Pruefung selbst leistet eine Fachkraft, optional ueber vermittelte Dienstleister.</p>', 'DGUV V3 Pruefung: Fristen und Nachweise dokumentieren', 'DGUV V3: Welche Nachweise Betriebe je Geraet vorhalten, wie Pruefintervalle zustande kommen und wie Protokolle pruefsicher abgelegt werden.', 220, 0],
        ['e-rechnung-pflicht-archivierung', 'E-Rechnung', 'E-Rechnung Pflicht und Archivierung', 'E-Rechnung 2025 bis 2028: Empfang, Ausstellung und GoBD-Archivierung', 'Die E-Rechnungspflicht kommt gestaffelt. Ueberblick ueber Fristen, Formate und die revisionssichere Ablage.', 'Belegakte besprechen', '/kontakt', '<h2>Der Fahrplan</h2><ul><li><strong>seit 01.01.2025:</strong> alle inlaendischen B2B-Unternehmen muessen E-Rechnungen empfangen koennen</li><li><strong>ab 01.01.2027:</strong> Ausstellungspflicht fuer Unternehmen mit mehr als 800.000 EUR Vorjahresumsatz</li><li><strong>ab 01.01.2028:</strong> Ausstellungspflicht fuer alle inlaendischen B2B-Umsaetze</li></ul><h2>Formate</h2><p>Zulaessig sind strukturierte Formate nach EN 16931, insbesondere XRechnung und ZUGFeRD ab Version 2.0.</p><h2>Archivierung (GoBD)</h2><ul><li>Aufbewahrung im strukturierten Originalformat, unveraenderbar</li><li>Rechnungen: Aufbewahrungsfrist seit 2025 acht Jahre</li><li>Verfahrensdokumentation, wie Rechnungen empfangen, geprueft und abgelegt werden</li></ul><p><strong>Hinweis:</strong> Allgemeine Information, keine Steuerberatung. Die Belegakte legt Eingangs- und Ausgangsrechnungen samt Quittungen revisionsnah ab und exportiert sie fuer die Kanzlei.</p>', 'E-Rechnung 2025 bis 2028: Pflichten, Formate und GoBD-Archivierung', 'E-Rechnung: Empfangspflicht seit 2025, Ausstellungspflicht bis 2028, Formate XRechnung und ZUGFeRD sowie GoBD-konforme Ablage.', 230, 0],
        ['ki-verordnung-nachweise-unternehmen', 'KI-Verordnung', 'KI-Verordnung Nachweise fuer Unternehmen', 'EU AI Act ab August 2026: KI-Register und Nachweise fuer Betreiber', 'Die EU-KI-Verordnung schafft neue Nachweispflichten. Ueberblick ueber Fristen, Betreiberpflichten und die Nachweisakte.', 'AI-Act-Modul vormerken', '/kontakt', '<h2>Worum es geht</h2><p>Die EU-KI-Verordnung (VO (EU) 2024/1689) gilt schrittweise. Zwei Punkte betreffen viele Unternehmen frueh: die KI-Kompetenz der Beschaeftigten und die Betreiberpflichten beim Einsatz von KI-Systemen.</p><h2>Wichtige Termine</h2><ul><li><strong>seit 02.02.2025:</strong> Beschaeftigte muessen ausreichende KI-Kompetenz haben; Schulungsmassnahmen sind nachzuweisen</li><li><strong>ab 02.08.2026:</strong> volle Anbieter- und Betreiberpflichten fuer Hochrisiko-KI</li></ul><h2>Typische Nachweise</h2><ul><li>KI-Register mit Systemen, Anwendungsfaellen und Verantwortlichen</li><li>Schulungsnachweise zur KI-Kompetenz</li><li>Logs, menschliche Aufsicht und Information Betroffener, wo erforderlich</li></ul><p><strong>Hinweis:</strong> Allgemeine Information, keine Rechtsberatung. Die Plattform fuehrt Register und Nachweise; die Einstufung der Risikoklasse trifft das Unternehmen mit seinen Beratern.</p>', 'EU AI Act ab 2026: KI-Register und Nachweise fuer Unternehmen', 'EU-KI-Verordnung: KI-Kompetenz seit 02/2025, Betreiberpflichten ab 08/2026 und welche Nachweise Unternehmen als Register fuehren sollten.', 240, 0],
        ['jahresabschluss-offenlegung-frist', 'Offenlegung', 'Jahresabschluss Offenlegung Frist', 'Jahresabschluss-Offenlegung: Fristen und Einreichungsbelege', 'Kapitalgesellschaften muessen ihren Jahresabschluss offenlegen. Ueberblick ueber Fristen, Ort der Einreichung und Belege.', 'Belegakte besprechen', '/kontakt', '<h2>Worum es geht</h2><p>Kapitalgesellschaften wie GmbH und UG muessen ihren Jahresabschluss offenlegen. Die Einreichung erfolgt seit 2022 elektronisch beim Unternehmensregister.</p><h2>Fristen</h2><ul><li>Regelfall: innerhalb von zwoelf Monaten nach dem Geschaeftsjahresende</li><li>kapitalmarktorientierte Gesellschaften: verkuerzte Frist</li></ul><h2>Bei Versaeumnis</h2><p>Das Bundesamt fuer Justiz leitet bei verspaeteter Offenlegung ein Ordnungsgeldverfahren ein. Ein dokumentierter Fristenkalender und der Einreichungsbeleg schuetzen vor unnoetigen Ordnungsgeldern.</p><h2>Typische Belege</h2><ul><li>Einreichungsbeleg bzw. Quittung des Unternehmensregisters</li><li>Feststellungsbeschluss zum Jahresabschluss</li><li>Fristenkalender mit Verantwortlichem</li></ul><p><strong>Hinweis:</strong> Allgemeine Information, keine Steuerberatung. Die Belegakte legt Quittungen und Beschluesse ab und erinnert an die naechste Frist.</p>', 'Jahresabschluss-Offenlegung: Fristen, Unternehmensregister und Belege', 'Offenlegung des Jahresabschlusses: Fristen, Einreichung beim Unternehmensregister, Ordnungsgeldrisiko und welche Belege in die Akte gehoeren.', 250, 0],
    ],

    // [slug, category, status, title, headline, summary, audience, includes_text, boundary_text, cta_label, cta_url, source_label, source_url, is_featured, is_active, sort_order]
    'modules' => [
        ['produkt-haendler-nachweisakte', 'Produkte und Handel', 'start', 'Produkt-/Haendler-Nachweisakte', 'Produktunterlagen, Registrierungen und Quellen je SKU ablegen', 'Fuer Haendler, Importeure und Marken: GPSR, VerpackG/LUCID, WEEE, Batterie, BFSG, Lieferantenunterlagen und Rueckrufordner als Nachweisakte. Optional Vermittlung passender Dienstleister fuer Verpackungslizenz oder Konformitaetspruefung.', 'Onlinehaendler, Importeure, D2C-Marken, Produktmanager, Agenturen und Berater.', 'Produktakte, Quellen, Registrierungsbelege, Lieferantennachweise, Rueckruf-/Marktueberwachungsordner.', 'Keine automatische Produktbewertung und keine Produktkonformitaetsfreigabe.', 'Produktakte anfragen', '/kontakt', 'EU Product Safety', 'https://commission.europa.eu/business-economy-euro/product-safety-and-requirements/product-safety_en', 1, 1, 10],
        ['prueffristen-tracker', 'Pruef- und Betreiberfristen', 'start', 'Pruef-/Fristen-Tracker', 'Wiederkehrende Pruefungen und Nachweise an einem Ort', 'DGUV-nahe Pruefungen, Feuerloescher, Leitern, Unterweisungen, Gebaeude- und Betreiberfristen werden als Fristen und Nachweisordner verwaltet. Bei faelligen Fristen optional Angebot passender Pruefdienstleister.', 'Betriebe mit Arbeitsmitteln, Standorten, Unterweisungen, Wartungen und Pruefbelegen.', 'Fristen, Verantwortliche, Dokumente, Portalbelege, Exportordner, Status offen/faellig/erledigt.', 'Keine Entscheidung, welche Pruefung gesetzlich im Einzelfall erforderlich ist. Nutzer oder Fachpartner legen Inhalte und Fristen fest.', 'Demo anfragen', '/kontakt', 'DGUV', 'https://www.dguv.de/', 1, 1, 20],
        ['ki-verordnung-nachweisakte', 'Datenschutz und IT', 'start', 'KI-Verordnung / AI-Act Nachweisakte', 'KI-Register, Schulungsnachweise und Betreiberpflichten dokumentieren', 'EU-KI-Verordnung: KI-Kompetenz-Nachweise (seit 02/2025) und Betreiberpflichten (ab 08/2026) als Register, Aufgaben- und Nachweisakte fuehren. Neue Pflicht ohne etablierten Wettbewerber.', 'Unternehmen, die KI-Systeme einsetzen: Marketing, HR, Support, Produktteams, Agenturen.', 'KI-Register, Anwendungsfaelle, Risikoklassen, Schulungsnachweise, Logs, Verantwortliche, Export.', 'Keine rechtliche Einstufung der Risikoklasse und keine Konformitaetsfreigabe durch die Plattform.', 'AI-Act-Modul vormerken', '/kontakt', 'EU-KI-Verordnung (VO 2024/1689)', 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj', 1, 1, 30],
        ['beraterzugang', 'Berater', 'start', 'Kanzlei- und Berater-Cockpit', 'Mandanten-Pflichten und Nachweise ueber alle Mandate im Blick', 'Steuerberater, Lohnbueros, Sifa, Pruefer und Fachberater sehen offene Nachweise je Mandant, fordern Belege an und exportieren fertige Nachweisordner. Das Cockpit ist der Multiplikator: die Kanzlei bucht, die Mandanten liefern.', 'Kanzleien, Lohnbueros, Sicherheitsfachkraefte, Pruefer und Fachberater mit vielen Mandanten.', 'Mandantenliste, offene Aufgaben je Mandant, Beleganforderung, Fristen, Export, Notizen, Rollen.', 'Die fachliche Bewertung trifft der Berater; die Plattform organisiert Nachweise und Fristen.', 'Kanzlei-Cockpit anfragen', '/kontakt', 'DSGVO Art. 28 (Auftragsverarbeitung)', 'https://dsgvo-gesetz.de/art-28-dsgvo/', 1, 1, 40],
        ['steuer-register-fristen', 'Steuern und Register', 'next', 'Steuer-/Registerfristen', 'Offenlegung, E-Rechnung und GoBD-Belege fuer die Kanzlei', 'Jahresabschluss- und Offenlegungsakte, E-Rechnung (Empfangspflicht seit 2025, Ausstellungspflicht gestaffelt bis 2028), TSE/GoBD-Belege und Portalquittungen als strukturierter Arbeitsordner.', 'GmbH, UG, Steuerberater, Lohnbueros, Buchhaltung und Finance-Teams.', 'Fristen, Belege, Einreichungsquittungen, Steuerberaterexport, Jahresordner.', 'Keine Steuerberatung, keine Abschlussfreigabe und keine automatische Einreichung.', 'Startpaket besprechen', '/kontakt', 'Unternehmensregister', 'https://www.unternehmensregister.de/', 0, 1, 50],
        ['bfsg-barrierefreiheit', 'Produkte und Handel', 'next', 'BFSG-Barrierefreiheitsakte', 'Shop- und Produktnachweise fuer Barrierefreiheit dokumentieren', 'BFSG wird als Quellen-, Aufgaben- und Nachweisakte gefuehrt: Testergebnisse, Screenshots, Issues, Verlauf und Beraterfreigaben.', 'Online-Shops, Agenturen, SaaS-Anbieter, Produktanbieter mit Verbraucherbezug.', 'Quellen, Tests, Issues, Screenshots, Status, Export.', 'Keine automatische BFSG-Einordnung und keine fachliche Freigabe der Barrierefreiheit.', 'BFSG-Modul vormerken', '/kontakt', 'Bundesfachstelle BFSG', 'https://www.bundesfachstelle-barrierefreiheit.de/DE/Barrierefreiheitsstaerkungsgesetz/FAQ/faq_node', 0, 1, 60],
        ['hinweisgeber-meldestelle', 'Arbeitgeber', 'partner', 'Hinweisgeber-Nachweisakte', 'Meldestellen-Unterlagen und Fristen strukturiert ablegen', 'HinSchG-nahe Unterlagen, Rollen, Anbieter, Fristen und Belege werden verwaltet. Die eigentliche Meldestelle kann ein Partner stellen.', 'Arbeitgeber ab relevanter Groesse, HR, Compliance, externe Meldestellenanbieter.', 'Rollen, Anbieter, Fristen, Richtlinien, Nachweise, Export.', 'Keine Rechtsberatung und keine eigene Meldestellenleistung im MVP.', 'Partnerloesung anfragen', '/kontakt', 'HinSchG', 'https://www.gesetze-im-internet.de/hinschg/BJNR08C0B0023.html', 0, 1, 70],
    ],

    // [owner_type, owner_slug, question, answer, sort_order]
    'faqs' => [
        ['global', '', 'Ist das Rechtsberatung?', 'Nein. Die Plattform verwaltet Fristen, Dokumente, Quellen, Portalbelege und Exporte. Fachliche oder rechtliche Bewertungen bleiben beim Betrieb und seinen Beratern.', 10],
        ['global', '', 'Kann ich Texte und Module spaeter ueberschreiben?', 'Ja. Seiten, Module, SEO-Daten, Quellen, Designwerte, Kontakt- und Rechtstexte sind im Admin editierbar.', 20],
        ['global', '', 'Was ist der wichtigste Nutzen?', 'Nicht das einmalige Lesen einer Pflicht, sondern das Wiederfinden von Nachweisen und das Erinnern an wiederkehrende Fristen.', 30],
    ],
];
