<?php
declare(strict_types=1);

/*
 * Gemeinsame Standard-Inhalte.
 *
 * Diese Datei ist die einzige Quelle fuer die Startinhalte. Sie wird von zwei
 * Stellen genutzt:
 *   1. app/schema.php (seed_defaults) schreibt sie beim Install in die Datenbank.
 *   2. app/helpers.php nutzt sie als Fallback, wenn keine Datenbank erreichbar
 *      ist (Vorschau-/Demo-Modus, z. B. bei einem Vercel-Deployment ohne MySQL).
 *
 * Positionierung: offensiv verkaufend ("einordnen, erledigen, nachweisen"),
 * bewusst in der zulaessigen Grauzone. Verbindliche Rechts-/Steuerberatung im
 * Einzelfall bleibt bei Partner-Kanzleien; keine Garantie-/Vollstaendigkeits-
 * versprechen. Schluessel, Slugs, URLs und Farbwerte bleiben ASCII, sichtbare
 * Texte sind UTF-8 mit Umlauten.
 */

return [
    // setting_key => [value, label, group, field_type]
    'settings' => [
        'site_name' => ['Unternehmenspflichten.de', 'Seitentitel', 'general', 'text'],
        'site_claim' => ['Unternehmenspflichten: eingeordnet, erledigt, nachgewiesen.', 'Hauptclaim', 'content', 'textarea'],
        'site_subclaim' => ['Wir zeigen dir, welche Fristen und Nachweise für deinen Betrieb zählen, besorgen Registrierungen, Lizenzen und Prüftermine über geprüfte Partner und liefern den Nachweisordner zum Export – von GPSR über Prüffristen bis zur Offenlegung.', 'Unterzeile', 'content', 'textarea'],
        'primary_cta_label' => ['Kostenlosen Pflichten-Check starten', 'Primärer Button', 'content', 'text'],
        'primary_cta_url' => ['/kontakt', 'Primärer Button-Link', 'content', 'text'],
        'secondary_cta_label' => ['Leistungen ansehen', 'Sekundärer Button', 'content', 'text'],
        'secondary_cta_url' => ['/module', 'Sekundärer Button-Link', 'content', 'text'],
        'hero_eyebrow' => ['Einordnen · Erledigen · Nachweisen', 'Hero Eyebrow', 'content', 'text'],
        'home_modules_heading' => ['Die Pflichten, die richtig wehtun, wenn man sie vergisst', 'Startseite: Modul-Überschrift', 'content', 'text'],
        'home_modules_intro' => ['Wir starten dort, wo Bußgeld, Abmahnung oder Ordnungsgeld drohen: Produkt- und Händlerpflichten, Prüf- und Betreiberfristen, Steuer- und Registertermine, KI-Verordnung. Orientierung, Erledigung und Nachweis aus einer Hand.', 'Startseite: Modul-Einleitung', 'content', 'textarea'],
        'home_modules_eyebrow' => ['Leistungen', 'Startseite: Modul-Eyebrow', 'content', 'text'],
        'home_process_heading' => ['In drei Schritten raus aus dem Pflichten-Chaos', 'Startseite: Ablauf-Überschrift', 'content', 'text'],
        'home_process_eyebrow' => ['So läuft es', 'Startseite: Ablauf-Eyebrow', 'content', 'text'],
        'home_step_1_title' => ['Pflichten-Check', 'Startseite: Schritt 1 Titel', 'content', 'text'],
        'home_step_1_text' => ['Sag uns Betrieb, Produkte und Standorte – wir zeigen dir konkret und mit Quellen, welche Fristen und Nachweise für dich zählen.', 'Startseite: Schritt 1 Text', 'content', 'textarea'],
        'home_step_2_title' => ['Erledigen lassen', 'Startseite: Schritt 2 Titel', 'content', 'text'],
        'home_step_2_text' => ['Registrierungen, Verpackungslizenzen und Prüftermine besorgen wir über geprüfte Partner. Kein Behördendeutsch, kein Recherchieren.', 'Startseite: Schritt 2 Text', 'content', 'textarea'],
        'home_step_3_title' => ['Nachweis sichern', 'Startseite: Schritt 3 Titel', 'content', 'text'],
        'home_step_3_text' => ['Belege, Quittungen und Fristen landen im Nachweisordner – exportierbar für Prüfer, Steuerberater, Sifa oder Auftraggeber.', 'Startseite: Schritt 3 Text', 'content', 'textarea'],
        'home_trust_heading' => ['Klare Ansage statt Paragrafen-Nebel', 'Startseite: Vertrauens-Überschrift', 'content', 'text'],
        'home_trust_eyebrow' => ['Warum wir', 'Startseite: Vertrauens-Eyebrow', 'content', 'text'],
        'faq_eyebrow' => ['FAQ', 'FAQ Eyebrow', 'content', 'text'],
        'faq_heading' => ['Häufige Fragen', 'FAQ Überschrift', 'content', 'text'],
        'legal_boundary' => ['Wir geben dir praxisnahe Orientierung und übernehmen das Operative wie Registrierungen, Fristen und Nachweise. Verbindliche Rechts- und Steuerberatung im Einzelfall übernehmen unsere Partner-Kanzleien.', 'Rechtsgrenze', 'content', 'textarea'],
        'contact_email' => ['kontakt@unternehmenspflichten.de', 'Kontakt E-Mail', 'contact', 'text'],
        'contact_phone' => ['', 'Telefon', 'contact', 'text'],
        'company_name' => ['Unternehmenspflichten.de', 'Betreibername', 'legal', 'text'],
        'company_address' => ['Bitte im Admin ersetzen', 'Anschrift', 'legal', 'textarea'],
        'pricing_note' => ['Vom günstigen Self-Service-Tool bis „wir erledigen alles". Registrierungen wie die Verpackungslizenz laufen oft ohne Aufpreis über unsere Partner. Finale Preise im Admin anpassbar.', 'Preishinweis', 'content', 'textarea'],
    ],

    // token_key => [value, label, field_type]
    'design' => [
        'color-bg' => ['#f6f7f4', 'Hintergrund', 'color'],
        'color-surface' => ['#ffffff', 'Fläche', 'color'],
        'color-text' => ['#17211d', 'Text', 'color'],
        'color-muted' => ['#5b6762', 'Sekundärtext', 'color'],
        'color-primary' => ['#0f5b55', 'Primärfarbe', 'color'],
        'color-primary-strong' => ['#0a413d', 'Primär dunkel', 'color'],
        'color-secondary' => ['#275f8f', 'Info-Blau', 'color'],
        'color-accent' => ['#c47a1b', 'Fristen-Akzent', 'color'],
        'color-danger' => ['#a63a2b', 'Überfällig', 'color'],
        'color-success' => ['#2f7d4f', 'Erledigt', 'color'],
        'font-head' => ['Inter, Arial, sans-serif', 'Schrift Überschriften', 'text'],
        'font-body' => ['Inter, Arial, sans-serif', 'Schrift Text', 'text'],
        'base-font-size' => ['16px', 'Basis-Schriftgröße', 'text'],
        'radius' => ['8px', 'Eckenradius', 'text'],
        'max-width' => ['1180px', 'Maximale Breite', 'text'],
    ],

    // [slug, nav_label, title, hero_title, hero_subtitle, cta_label, cta_url, body_html, meta_title, meta_description, sort_order, show_in_nav]
    'pages' => [
        ['home', 'Start', 'Unternehmenspflichten: Fristen, Nachweise und Erledigung aus einer Hand', 'Unternehmenspflichten: eingeordnet, erledigt, nachgewiesen.', 'Wir zeigen dir, welche Fristen und Nachweise für deinen Betrieb zählen, besorgen Registrierungen, Lizenzen und Prüftermine über geprüfte Partner und liefern den Nachweisordner zum Export.', 'Pflichten-Check starten', '/kontakt', '<h2>Was wir für dich tun</h2><p>Unternehmenspflichten.de nimmt dir die wiederkehrende Pflicht-Arbeit ab: Wir ordnen ein, was für deinen Betrieb zählt, erinnern an jede Frist, besorgen Registrierungen, Lizenzen und Prüftermine über unser Partnernetz und legen alle Nachweise sauber ab.</p><p>Am Ende hast du einen Exportordner, den du Prüfern, dem Steuerberater, der Sifa oder Auftraggebern in die Hand gibst – ohne Suchen, ohne Lücken.</p>', 'Unternehmenspflichten erledigen lassen – Fristen, Nachweise, Lizenzen', 'Pflichten-Check, Erledigung über Partner und ein Nachweisordner zum Export: GPSR, VerpackG/LUCID, Prüffristen, Offenlegung und mehr – aus einer Hand.', 1, 1],
        ['module', 'Leistungen', 'Leistungen: einordnen, erledigen, nachweisen', 'Von der Produktakte bis zur Prüffrist', 'Wir kümmern uns um die Pflichten, die Geld kosten, wenn sie liegen bleiben – mit dir oder für dich.', 'Pflichten-Check starten', '/kontakt', '<p>Jede Leistung gibt es in drei Stufen: <strong>selbst machen</strong> mit unserem Tool, <strong>erledigen lassen</strong> über unser Partnernetz oder <strong>begleiten lassen</strong> mit Fachpartnern. Du entscheidest, wie viel du abgibst.</p>', 'Leistungen von Unternehmenspflichten.de', 'GPSR, Verpackung/LUCID, Prüffristen, Steuer- und Registertermine, KI-Verordnung und mehr – einordnen, erledigen, nachweisen.', 2, 1],
        ['berater', 'Für Berater', 'Kanzlei- und Berater-Portal', 'Mehr Mandanten-Nachweise, weniger Hinterhertelefonieren', 'Steuerberater, Sifa, Lohnbüros und Fachberater sehen offene Pflichten je Mandant, fordern Belege an und exportieren fertige Ordner – und geben die Nutzung weiter.', 'Als Kanzlei starten', '/kontakt', '<p>Das Portal ist dein Umsatzhebel: Mandanten liefern Belege selbst, du behältst alle Fristen im Blick und lieferst fertige Exporte – ohne E-Mail-Ping-Pong. Konditionen für Partner auf Anfrage.</p>', 'Kanzlei- und Berater-Portal – Mandantenpflichten im Blick', 'Für Steuerberater, Sifa und Fachberater: Mandantenpflichten, Fristen und Nachweise strukturieren, anfordern und exportieren.', 3, 1],
        ['preise', 'Preise', 'Preise und Pakete', 'Bezahl nur, was du abgibst', 'Vom günstigen Self-Service bis „wir erledigen alles". Lizenzen und Prüfungen oft ohne Aufpreis über unsere Partner.', 'Angebot anfragen', '/kontakt', '<h2>Drei Wege</h2><ul><li><strong>Self-Service</strong> – das Tool für Fristen, Belege und Export. Für Betriebe, die selbst Hand anlegen.</li><li><strong>Erledigt-für-dich</strong> – wir übernehmen Registrierungen, Lizenzen und Prüftermine über geprüfte Partner. Einrichtung plus Monatspauschale.</li><li><strong>Berater-Paket</strong> – Mandantenverwaltung für Kanzleien und Fachberater.</li></ul><p>Viele Registrierungen wie die Verpackungslizenz laufen ohne Aufpreis über unsere Partner – wir verdienen an der Vermittlung, nicht an dir. Konkrete Preise stimmen wir auf Betrieb, Standorte und Umfang ab.</p>', 'Preise – Unternehmenspflichten.de', 'Self-Service, Erledigt-für-dich und Berater-Pakete. Registrierungen oft ohne Aufpreis über Partner.', 4, 1],
        ['kontakt', 'Kontakt', 'Pflichten-Check anfragen', 'Sag uns, wo es klemmt – wir sagen dir, was zu tun ist', 'Kurz Betrieb, Branche und Produkte beschreiben. Du bekommst eine erste Einordnung und ein konkretes Angebot.', 'Nachricht senden', '#kontaktformular', '<p>Wir melden uns mit einer ersten Einordnung deiner Pflichten und einem Vorschlag, was du selbst machst und was wir übernehmen. Kein Abo-Zwang.</p>', 'Kontakt und Pflichten-Check – Unternehmenspflichten.de', 'Pflichten-Check, Angebot oder Beraterzugang anfragen.', 5, 1],
        ['impressum', 'Impressum', 'Impressum', 'Angaben gemäß DDG', 'Diese Angaben sind Platzhalter und müssen vor dem Live-Betrieb im Admin ersetzt werden.', null, null, '<p><strong>Betreiber:</strong> Bitte im Admin ersetzen</p><p><strong>Anschrift:</strong> Bitte im Admin ersetzen</p><p><strong>E-Mail:</strong> kontakt@unternehmenspflichten.de</p>', 'Impressum', 'Impressum von Unternehmenspflichten.de.', 90, 0],
        ['datenschutz', 'Datenschutz', 'Datenschutzerklärung', 'Datenschutz und Kontaktanfragen', 'Diese Datenschutzerklärung ist ein editierbarer Starttext und muss vor dem Live-Betrieb final geprüft werden.', null, null, '<h2>Kontaktformular</h2><p>Wenn Sie das Kontaktformular nutzen, speichern wir Ihre Angaben zur Bearbeitung der Anfrage.</p><h2>Server-Logs</h2><p>Der Hostinganbieter kann technische Zugriffsdaten verarbeiten. Details müssen nach Hosting-Konfiguration ergänzt werden.</p><h2>Keine automatische Bewertung</h2><p>Die Plattform organisiert Fristen, Dokumente und Nachweise. Verbindliche Rechts- und Steuerfragen übernehmen Partner-Kanzleien.</p>', 'Datenschutz', 'Datenschutzhinweise für Unternehmenspflichten.de.', 91, 0],
        ['ratgeber', 'Ratgeber', 'Ratgeber zu Unternehmenspflichten', 'Ratgeber: Pflichten, Fristen und Nachweise', 'Konkrete Antworten zu wiederkehrenden Pflichten – und was du dafür vorhalten solltest.', 'Pflichten-Check starten', '/kontakt', '<p>Kurz und konkret: was gilt, welche Fristen und Nachweise wichtig sind und wie du die Belege sauber ablegst. Bei Rechtsfragen im Detail holen wir Partner-Kanzleien dazu.</p>', 'Ratgeber zu Unternehmenspflichten, Fristen und Nachweisen', 'Konkrete Ratgeber zu GPSR, LUCID, DGUV V3, E-Rechnung, KI-Verordnung und Offenlegung: Pflichten, Fristen und die richtigen Nachweise.', 6, 1],
        ['gpsr-nachweispflichten-haendler', 'GPSR-Nachweise', 'GPSR Nachweispflichten für Händler', 'GPSR: Welche Nachweise muss ich als Händler vorhalten?', 'Seit dem 13.12.2024 gilt die EU-Produktsicherheitsverordnung (GPSR). Wir ordnen ein, was für deine Produkte zählt, und bauen die Akte.', 'GPSR erledigen lassen', '/kontakt', '<h2>Worum es geht</h2><p>Die EU-Produktsicherheitsverordnung (GPSR, Verordnung (EU) 2023/988) gilt seit dem 13. Dezember 2024 für nahezu alle Verbraucherprodukte ohne eigene Spezialvorschrift. Sie verpflichtet Hersteller, Importeure und Händler zu Sicherheit, Rückverfolgbarkeit und Information.</p><h2>Typische Nachweise, die Händler vorhalten</h2><ul><li>verantwortliche Person mit Sitz in der EU je Produkt</li><li>Herstellerangaben sowie Typen-, Chargen- oder Seriennummer zur Rückverfolgbarkeit</li><li>Sicherheits- und Warnhinweise sowie Anleitung in Landessprache</li><li>technische Unterlagen bzw. Nachweise vom Vorlieferanten</li><li>Dokumentation von Beschwerden, Rücknahmen und Korrekturmaßnahmen</li></ul><h2>Häufige Fragen</h2><h3>Brauche ich für jedes Produkt einen EU-Ansprechpartner?</h3><p>Für Produkte aus Drittländern muss ein Wirtschaftsakteur mit Sitz in der EU benannt und erreichbar sein. Ohne diesen darf das Produkt nicht angeboten werden.</p><h3>Was droht bei Verstößen?</h3><p>Marktüberwachung, Verkaufsstopp und Abmahnungen sind möglich. Erste Abmahnungen wegen fehlender GPSR-Angaben sind dokumentiert.</p><p><strong>So helfen wir:</strong> Wir ordnen ein, was für deine Produkte gilt, bauen die Produktakte je SKU und erinnern an offene Punkte. Rechtliche Detailfragen klären unsere Partner-Kanzleien.</p>', 'GPSR Nachweispflichten für Händler und Importeure', 'GPSR ab 12/2024: Welche Nachweise Händler und Importeure vorhalten und wie du eine prüffeste Produktakte aufbaust.', 200, 0],
        ['lucid-verpackungsregister-nachweis', 'LUCID/VerpackG', 'LUCID und VerpackG Nachweise', 'LUCID/VerpackG: Registrierung, Lizenz und Nachweise richtig ablegen', 'Registrierung, Systembeteiligung und Mengenmeldung erzeugen Belege, die dauerhaft auffindbar sein müssen. Wir besorgen die Lizenz über Partner und legen die Belege ab.', 'Verpackung erledigen lassen', '/kontakt', '<h2>Die drei Pflichtschritte</h2><ul><li><strong>Registrierung</strong> im Verpackungsregister LUCID bei der Zentralen Stelle vor dem Inverkehrbringen</li><li><strong>Systembeteiligung</strong> (Lizenzierung) der Verpackungsmengen bei einem dualen System</li><li><strong>Datenmeldung</strong> der lizenzierten Mengen an LUCID</li></ul><h2>Typische Belege in der Akte</h2><ul><li>LUCID-Registriernummer und Registrierungsbestätigung</li><li>Lizenz- bzw. Beteiligungsvertrag mit dem dualen System</li><li>Mengenmeldungen und Jahresabschluss-Mengen</li><li>bei Überschreiten der Schwellen: Vollständigkeitserklärung</li></ul><h2>Ausblick</h2><p>Ab August 2026 löst die EU-Verpackungsverordnung (PPWR) schrittweise das VerpackG ab. Bestehende Registrierungen und Belege sollten geordnet vorliegen, um den Übergang nachvollziehbar zu halten.</p><p><strong>So helfen wir:</strong> Die Lizenz vermitteln wir über unsere Partner – häufig ohne Aufpreis für dich –, legen alle Belege ab und erinnern an die Mengenmeldung.</p>', 'LUCID und VerpackG: Registrierung, Lizenz und Nachweise', 'LUCID-Registrierung, Systembeteiligung und Mengenmeldung: welche Belege Händler ablegen und wie der PPWR-Übergang vorbereitet wird.', 210, 0],
        ['dguv-v3-pruefung-nachweis', 'DGUV V3', 'DGUV V3 Prüfung Nachweis', 'DGUV V3 Prüfung: Fristen und Nachweise dokumentieren', 'Elektrische Betriebsmittel müssen regelmäßig geprüft und die Prüfung dokumentiert werden. Wir organisieren Fristen, Prüftermin und Nachweis.', 'Prüffristen abgeben', '/kontakt', '<h2>Worum es geht</h2><p>Die DGUV Vorschrift 3 verlangt die regelmäßige Prüfung ortsveränderlicher und ortsfester elektrischer Betriebsmittel durch eine Elektrofachkraft. Die konkreten Prüfintervalle ergeben sich aus der Gefährdungsbeurteilung und den technischen Regeln (u. a. TRBS 1201/1203).</p><h2>Typische Nachweise</h2><ul><li>Prüfprotokoll je Gerät oder Anlage mit Ergebnis und Datum</li><li>Angaben zur prüfenden Elektrofachkraft</li><li>Mängel- und Maßnahmenliste</li><li>nächster Prüftermin und Verantwortlicher</li></ul><h2>Häufige Fragen</h2><h3>Wie oft muss geprüft werden?</h3><p>Es gibt keine starre Einheitsfrist. Der Intervall folgt aus der Gefährdungsbeurteilung; Richtwerte je Geräteart dienen als Orientierung.</p><h3>Wer darf prüfen?</h3><p>Nur eine qualifizierte Elektrofachkraft nach den anerkannten Regeln der Technik.</p><p><strong>So helfen wir:</strong> Wir verwalten Fristen und Protokolle und vermitteln bei Fälligkeit einen passenden Prüfdienstleister aus unserem Partnernetz.</p>', 'DGUV V3 Prüfung: Fristen und Nachweise dokumentieren', 'DGUV V3: Welche Nachweise Betriebe je Gerät vorhalten, wie Prüfintervalle zustande kommen und wie Protokolle prüffest abgelegt werden.', 220, 0],
        ['e-rechnung-pflicht-archivierung', 'E-Rechnung', 'E-Rechnung Pflicht und Archivierung', 'E-Rechnung 2025 bis 2028: Empfang, Ausstellung und GoBD-Archivierung', 'Die E-Rechnungspflicht kommt gestaffelt. Wir bringen Fristen, Formate und die revisionssichere Ablage in Ordnung.', 'E-Rechnung vorbereiten', '/kontakt', '<h2>Der Fahrplan</h2><ul><li><strong>seit 01.01.2025:</strong> alle inländischen B2B-Unternehmen müssen E-Rechnungen empfangen können</li><li><strong>ab 01.01.2027:</strong> Ausstellungspflicht für Unternehmen mit mehr als 800.000 EUR Vorjahresumsatz</li><li><strong>ab 01.01.2028:</strong> Ausstellungspflicht für alle inländischen B2B-Umsätze</li></ul><h2>Formate</h2><p>Zulässig sind strukturierte Formate nach EN 16931, insbesondere XRechnung und ZUGFeRD ab Version 2.0.</p><h2>Archivierung (GoBD)</h2><ul><li>Aufbewahrung im strukturierten Originalformat, unveränderbar</li><li>Rechnungen: Aufbewahrungsfrist seit 2025 acht Jahre</li><li>Verfahrensdokumentation, wie Rechnungen empfangen, geprüft und abgelegt werden</li></ul><p><strong>So helfen wir:</strong> Wir legen Eingangs- und Ausgangsrechnungen samt Quittungen revisionsnah ab und exportieren sie für die Kanzlei. Steuerliche Detailfragen übernimmt dein Steuerberater oder unsere Partnerkanzlei.</p>', 'E-Rechnung 2025 bis 2028: Pflichten, Formate und GoBD-Archivierung', 'E-Rechnung: Empfangspflicht seit 2025, Ausstellungspflicht bis 2028, Formate XRechnung und ZUGFeRD sowie GoBD-konforme Ablage.', 230, 0],
        ['ki-verordnung-nachweise-unternehmen', 'KI-Verordnung', 'KI-Verordnung Nachweise für Unternehmen', 'EU AI Act ab August 2026: KI-Register und Nachweise für Betreiber', 'Die EU-KI-Verordnung schafft neue Nachweispflichten. Wir bauen dein KI-Register und die Nachweisakte – als einer der Ersten am Markt.', 'AI-Act-Akte starten', '/kontakt', '<h2>Worum es geht</h2><p>Die EU-KI-Verordnung (VO (EU) 2024/1689) gilt schrittweise. Zwei Punkte betreffen viele Unternehmen früh: die KI-Kompetenz der Beschäftigten und die Betreiberpflichten beim Einsatz von KI-Systemen.</p><h2>Wichtige Termine</h2><ul><li><strong>seit 02.02.2025:</strong> Beschäftigte müssen ausreichende KI-Kompetenz haben; Schulungsmaßnahmen sind nachzuweisen</li><li><strong>ab 02.08.2026:</strong> volle Anbieter- und Betreiberpflichten für Hochrisiko-KI</li></ul><h2>Typische Nachweise</h2><ul><li>KI-Register mit Systemen, Anwendungsfällen und Verantwortlichen</li><li>Schulungsnachweise zur KI-Kompetenz</li><li>Logs, menschliche Aufsicht und Information Betroffener, wo erforderlich</li></ul><p><strong>So helfen wir:</strong> Wir führen Register und Nachweise und erinnern an Fristen. Die rechtliche Einstufung der Risikoklasse bestätigt ein Partner.</p>', 'EU AI Act ab 2026: KI-Register und Nachweise für Unternehmen', 'EU-KI-Verordnung: KI-Kompetenz seit 02/2025, Betreiberpflichten ab 08/2026 und welche Nachweise Unternehmen als Register führen sollten.', 240, 0],
        ['jahresabschluss-offenlegung-frist', 'Offenlegung', 'Jahresabschluss Offenlegung Frist', 'Jahresabschluss-Offenlegung: Fristen und Einreichungsbelege', 'Kapitalgesellschaften müssen ihren Jahresabschluss offenlegen. Wir behalten die Frist im Blick und sichern den Einreichungsbeleg.', 'Offenlegung im Blick behalten', '/kontakt', '<h2>Worum es geht</h2><p>Kapitalgesellschaften wie GmbH und UG müssen ihren Jahresabschluss offenlegen. Die Einreichung erfolgt seit 2022 elektronisch beim Unternehmensregister.</p><h2>Fristen</h2><ul><li>Regelfall: innerhalb von zwölf Monaten nach dem Geschäftsjahresende</li><li>kapitalmarktorientierte Gesellschaften: verkürzte Frist</li></ul><h2>Bei Versäumnis</h2><p>Das Bundesamt für Justiz leitet bei verspäteter Offenlegung ein Ordnungsgeldverfahren ein. Ein dokumentierter Fristenkalender und der Einreichungsbeleg schützen vor unnötigen Ordnungsgeldern.</p><h2>Typische Belege</h2><ul><li>Einreichungsbeleg bzw. Quittung des Unternehmensregisters</li><li>Feststellungsbeschluss zum Jahresabschluss</li><li>Fristenkalender mit Verantwortlichem</li></ul><p><strong>So helfen wir:</strong> Wir erinnern an die Frist und legen Quittungen und Beschlüsse ab. Die Erstellung des Abschlusses übernimmt dein Steuerberater oder unsere Partnerkanzlei.</p>', 'Jahresabschluss-Offenlegung: Fristen, Unternehmensregister und Belege', 'Offenlegung des Jahresabschlusses: Fristen, Einreichung beim Unternehmensregister, Ordnungsgeldrisiko und welche Belege in die Akte gehören.', 250, 0],
    ],

    // [slug, category, status, title, headline, summary, audience, includes_text, boundary_text, cta_label, cta_url, source_label, source_url, is_featured, is_active, sort_order]
    'modules' => [
        ['produkt-haendler-nachweisakte', 'Produkte und Handel', 'start', 'Produkt-/Händler-Nachweisakte', 'Produktunterlagen, Registrierungen und Quellen je SKU – erledigt', 'Für Händler, Importeure und Marken: Wir ordnen die Produktpflichten ein (GPSR, VerpackG/LUCID, WEEE, Batterie, BFSG), besorgen Verpackungslizenz und Registrierungen über Partner und bauen die Produktakte je SKU – inklusive Rückrufordner.', 'Onlinehändler, Importeure, D2C-Marken, Produktmanager, Agenturen und Berater.', 'Produktakte, Quellen, Registrierungsbelege, Lieferantennachweise, Rückruf- und Marktüberwachungsordner.', 'Verbindliche Rechtsfragen klären unsere Partner-Kanzleien; Registrierung und Aktenführung übernehmen wir.', 'GPSR & Verpackung erledigen', '/kontakt', 'EU Product Safety', 'https://commission.europa.eu/business-economy-euro/product-safety-and-requirements/product-safety_en', 1, 1, 10],
        ['prueffristen-tracker', 'Prüf- und Betreiberfristen', 'start', 'Prüf-/Fristen-Tracker', 'Wiederkehrende Prüfungen und Nachweise an einem Ort', 'DGUV-nahe Prüfungen, Feuerlöscher, Leitern, Unterweisungen und Gebäude-/Betreiberfristen als Fristen und Nachweisordner. Wird eine Frist fällig, vermitteln wir den passenden Prüfdienstleister.', 'Betriebe mit Arbeitsmitteln, Standorten, Unterweisungen, Wartungen und Prüfbelegen.', 'Fristen, Verantwortliche, Dokumente, Portalbelege, Exportordner, Status offen/fällig/erledigt.', 'Welche Prüfung im Einzelfall Pflicht ist, klären wir mit dir und Fachpartnern; Termine und Nachweise organisieren wir.', 'Prüffristen abgeben', '/kontakt', 'DGUV', 'https://www.dguv.de/', 1, 1, 20],
        ['ki-verordnung-nachweisakte', 'Datenschutz und IT', 'start', 'KI-Verordnung / AI-Act Nachweisakte', 'KI-Register, Schulungsnachweise und Betreiberpflichten dokumentieren', 'EU-KI-Verordnung: KI-Kompetenz-Nachweise (seit 02/2025) und Betreiberpflichten (ab 08/2026) als Register, Aufgaben- und Nachweisakte. Neue Pflicht, noch ohne etablierten Wettbewerber.', 'Unternehmen, die KI-Systeme einsetzen: Marketing, HR, Support, Produktteams, Agenturen.', 'KI-Register, Anwendungsfälle, Risikoklassen, Schulungsnachweise, Logs, Verantwortliche, Export.', 'Die rechtliche Risikoklassen-Einstufung bestätigt ein Partner; Register, Nachweise und Erinnerungen liefern wir.', 'AI-Act-Akte starten', '/kontakt', 'EU-KI-Verordnung (VO 2024/1689)', 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj', 1, 1, 30],
        ['beraterzugang', 'Berater', 'start', 'Kanzlei- und Berater-Cockpit', 'Mandanten-Pflichten und Nachweise über alle Mandate im Blick', 'Steuerberater, Lohnbüros, Sifa und Fachberater sehen offene Nachweise je Mandant, fordern Belege an und exportieren fertige Ordner. Der Kanal ist der Multiplikator: die Kanzlei bucht, die Mandanten liefern.', 'Kanzleien, Lohnbüros, Sicherheitsfachkräfte, Prüfer und Fachberater mit vielen Mandanten.', 'Mandantenliste, offene Aufgaben je Mandant, Beleganforderung, Fristen, Export, Notizen, Rollen.', 'Die fachliche Bewertung trifft der Berater; wir liefern Struktur, Fristen und Export.', 'Kanzlei-Zugang anfragen', '/kontakt', 'DSGVO Art. 28 (Auftragsverarbeitung)', 'https://dsgvo-gesetz.de/art-28-dsgvo/', 1, 1, 40],
        ['steuer-register-fristen', 'Steuern und Register', 'next', 'Steuer-/Registerfristen', 'Offenlegung, E-Rechnung und GoBD-Belege für die Kanzlei', 'Jahresabschluss- und Offenlegungsakte, E-Rechnung (Empfang seit 2025, Ausstellung gestaffelt bis 2028), TSE/GoBD-Belege und Portalquittungen als Arbeitsordner.', 'GmbH, UG, Steuerberater, Lohnbüros, Buchhaltung und Finance-Teams.', 'Fristen, Belege, Einreichungsquittungen, Steuerberaterexport, Jahresordner.', 'Steuerliche Detailfragen übernimmt dein Steuerberater oder unsere Partnerkanzlei; wir organisieren Fristen und Belege.', 'Startpaket besprechen', '/kontakt', 'Unternehmensregister', 'https://www.unternehmensregister.de/', 0, 1, 50],
        ['bfsg-barrierefreiheit', 'Produkte und Handel', 'next', 'BFSG-Barrierefreiheitsakte', 'Shop- und Produktnachweise für Barrierefreiheit dokumentieren', 'BFSG als Quellen-, Aufgaben- und Nachweisakte: Testergebnisse, Screenshots, Issues, Verlauf und Freigaben. Wir strukturieren, Fachpartner testen und geben frei.', 'Online-Shops, Agenturen, SaaS-Anbieter, Produktanbieter mit Verbraucherbezug.', 'Quellen, Tests, Issues, Screenshots, Status, Export.', 'Die rechtliche BFSG-Einordnung bestätigt ein Partner; Tests, Aufgaben und Nachweise verwalten wir.', 'BFSG-Akte vormerken', '/kontakt', 'Bundesfachstelle BFSG', 'https://www.bundesfachstelle-barrierefreiheit.de/DE/Barrierefreiheitsstaerkungsgesetz/FAQ/faq_node', 0, 1, 60],
        ['hinweisgeber-meldestelle', 'Arbeitgeber', 'partner', 'Hinweisgeber-Nachweisakte', 'Meldestellen-Unterlagen und Fristen strukturiert ablegen', 'HinSchG-nahe Unterlagen, Rollen, Anbieter, Fristen und Belege verwalten. Die eigentliche Meldestelle stellt ein Partner.', 'Arbeitgeber ab relevanter Größe, HR, Compliance, externe Meldestellenanbieter.', 'Rollen, Anbieter, Fristen, Richtlinien, Nachweise, Export.', 'Rechtsfragen und die Meldestelle selbst laufen über Partner; Unterlagen und Fristen bei uns.', 'Partnerlösung anfragen', '/kontakt', 'HinSchG', 'https://www.gesetze-im-internet.de/hinschg/BJNR08C0B0023.html', 0, 1, 70],
    ],

    // [owner_type, owner_slug, question, answer, sort_order]
    'faqs' => [
        ['global', '', 'Ist das Rechtsberatung?', 'Wir geben dir praxisnahe Orientierung und übernehmen das Operative wie Registrierungen, Fristen und Nachweise. Verbindliche Rechts- oder Steuerberatung im Einzelfall übernehmen unsere Partner-Kanzleien.', 10],
        ['global', '', 'Was kostet das?', 'Vom günstigen Self-Service-Tool bis „wir erledigen alles". Viele Registrierungen laufen ohne Aufpreis über unsere Partner. Das genaue Angebot kommt aus dem Pflichten-Check.', 20],
        ['global', '', 'Was habe ich davon?', 'Keine verpasste Frist, kein fehlender Nachweis, kein Behörden-Recherche-Frust – und ein Exportordner, der jede Prüfung übersteht.', 30],
    ],
];
